version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: playground
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080